### ISSUE TITLE
wrong link on official websie 

### ISSUE THREAD

**Issue by iDevIt007** [spicecrm/spicecrm_fe_release_core#1]
Link for frontend listed on https://www.spicecrm.io/downloads/ is **wrong** and href leads back to backend repository instead of frontend.
You should update the webpage as soon as possible

BR

**Comment by christianknoll** [comment]
> Link for frontend listed on https://www.spicecrm.io/downloads/ is **wrong** and href leads back to backend repository instead of frontend.
> You should update the webpage as soon as possible

Thank you .. changed it.
