### ISSUE TITLE
Reports with Google charts

### ISSUE THREAD

**Issue by aleksandra-mazurek** [spicecrm/spicecrm_fe_release_core#13]
Throws error in the js:
core.umd.min.js:563 ERROR ReferenceError: google is not defined
    at ReporterDetailVisualizationGooglecharts.ngAfterViewInit (modulereports.js:14)

**Comment by christianknoll** [comment]
added an entry for the libloader in the reference database: 

REPLACE INTO `sysuilibs` (`id`, `name`, `src`, `version`, `package`, `rank`) VALUES ('24930C6C-2F4D-496F-B808-1DD62A405421', 'googlecharts', 'https://www.gstatic.com/charts/loader.js', '2019.06.001', 'core', 0);

and alsopushed a change to the dev factory branch. With that change the lib shoudl be (lazy)loaded properly.
