### ISSUE TITLE
Dashboard - Assistant filter - Translation

### ISSUE THREAD

**Issue by szymon-ryddza** [spicecrm/spicecrm_fe_release_core#14]
There is a problem with translation in an Assistant filtering (located on a dashboard). We have an ability to select couple modules (including Reminders). Reminders technicaly is not a Sugar module. That might be the reason why this particular entry is not translated correctly. 
We have a suspicion that translation engine in this case refers to $app_list_strings from backend (beanList or moduleList). Reminders is not a bean-like module so there is no coresponding translation.

Do you think that adding this missing entry in $app_list_strings on a backend side could resolve that problem (and will not generate additional ones)? Maybe you have some other solution for that problem?

**Comment by christianknoll** [comment]
we can just add Reminders to the sysmodules tbale and hide it and not associate a bean to it but still a label. 

INSERT INTO `sysmodules` (`id`, `module`, `module_label`, `singular`, `singular_label`, `icon`, `bean`, `beanfile`, `beantable`, `visible`, `track`, `favorites`, `actionset`, `duplicatecheck`, `tagging`, `workflow`, `version`, `package`, `acl`) VALUES ('6c1259ac-0d48-3943-ad07-fe16f413f9c6', 'Reminders', 'LBL_REMINDERS', NULL, 'LBL_REMINDER', NULL, NULL, NULL, NULL, '0', 0, 0, NULL, NULL, 0, 0, '2019.06.001', 'core', 1);


that ios what I did so the translation for the label LBL_REMINDERS will properly be used. Added that also to the reference DB. to be pushed with the next release.

**Comment by christianknoll** [comment]
in general to the assistant: there is some work left to do. we mive the activities and history to use the FTS and the same shoudl happen with the activits stream. Still an open known issue so this will change in the not too distant future anyway and make the assistant more flexible.

**Comment by szymon-ryddza** [comment]
Ok, looks like it worked :)

Thank you for your help and quick response.
