### ISSUE TITLE
Spice Path With Coaching and Kanban View vs. Translation and Currencies

### ISSUE THREAD

**Issue by aleksandra-mazurek** [spicecrm/spicecrm_fe_release_core#2]
It seems that Kanban view as well as 'Coaching' widget in Opportunities cannot be translated.  We have created proper entries in tables related to spicebeanguides, and it kind of works on backend (the Coaching widget) but it does not work on frontend. 

Additionally in Opportunities Kanban  summations are always presented as €

**Comment by christianknoll** [comment]
on the translation .. changed that adding a field stage_label to table spicebeanguidestages. This has also been updated and maintained in the reference database - so pulling from the reference will pull default labels and the new settings for the stages. The labels can then be transltaed using the regular label manager. 

The change has been pushed to the dev repository and will be released here with the next core release.

**Comment by christianknoll** [comment]
On the currency - we can only aggregate in one currency - which shoudl be the default currency of the system. Is this always presented in Euro also when yoiu change the systenm default currency?

**Comment by aleksandra-mazurek** [comment]
We will check the stage_label. But what about those other aspects: we created proper entries with pl_pl in: spicebeanguidestages_check_texts, and spicebeanguidestages_texts but it does not pull those translations to the opportunity detail view.

As for currency, yes we had $ set up as default currency but it has Euro hardcoded in templates. 
IT would be great if it used user preffered currency.

**Comment by christianknoll** [comment]
spicebeanguidestages_texts  came from the time when we built this for the old UI ... if the stage_label  is defined then the SpiceUI will pull the proper translation for the label. so then this can be translated and customized using the standard labels feature. We need to do the same for the checks.

**Comment by christianknoll** [comment]
Currency - that should be changed to use the system default currency.

**Comment by christianknoll** [comment]
pushed a fix to display the system default currency ... as discussed it would be nice to add a feature to convert that to the users default currency ... that is for a future release

**Comment by christianknoll** [comment]
also added now the support to translate labels for the checks.
