### ISSUE TITLE
Google Api Key Configuration

### ISSUE THREAD

**Issue by sscheuring** [spicecrm/spicecrm_fe_release_core#23]
Hi! 

I like the Google-Feature to complete a Account address (found here: https://www.spicecrm.io/tipstricks-google-search-and-complete/). We have Google API Access and (hopefully) the right token. Where can i configure the API Key?
Thx,
Sebastian

**Comment by maretval** [comment]
Hi Sebastian,

open config_override.php and enter variable
$sugar_config['googleapikey'] = 'YourGoogleAPIKey; 

Regards,
Val

**Comment by sscheuring** [comment]
Hi Val!

Thx for the fast feedback. I'll give it a try :)!
Regards, 
Sebastian

**Comment by christianknoll** [comment]
also moved this to a new component in the admin section with the upcoming release so all Google API settings can be maintained from within the UI
