### ISSUE TITLE
Validation does not work at create view

### ISSUE THREAD

**Issue by MichalNowacki** [spicecrm/spicecrm_fe_release_core#24]
When user create record by create view, system does not valid a form. So we can create record without name.
![screenshot-wisla71 int evolpe net-2019 07 15-13-55-37](https://user-images.githubusercontent.com/21124831/61214541-7077ff00-a708-11e9-8c41-c3bf8742927d.png)
![screenshot-wisla71 int evolpe net-2019 07 15-13-55-54](https://user-images.githubusercontent.com/21124831/61214554-7b329400-a708-11e9-956e-854752a06326.png)

**Comment by christianknoll** [comment]
pushed a change to the development factory to fix this and added validatioon oint he save of the docked composer. Still open is the duplicate check .. that is a bit tricks in the small composer. Will need to find a solution for that omne as well.
