### ISSUE TITLE
systeminputtimezones - Missing America timezones.

### ISSUE THREAD

**Issue by sodakjackman** [spicecrm/spicecrm_fe_release_core#27]
The labels for moment's timezones are language specific. Since systeminputtimezones uses a regex to determine which timezones to include in the component, the regex should honor various translations of timezone names.

https://github.com/spicecrm/spicecrm_fe_release_core/blob/master/src/systemcomponents/components/systeminputtimezone.ts

Line 67:

        this.timezones = this.timezones.filter( ( timezone: string ) => {
            return timezone.match(/^((Africa|Amerika|Antarctica|Arctic|Asia|Atlantic|Australia|Europe|Pacific)\/.+|UTC)$/);
        });

Needs to include "America" in the regex match so when locale is English, the America timezones are included.

**Comment by christianknoll** [comment]
thank you .. pulled it into the core and will be also part of the upcomifng release.
