### ISSUE TITLE
Log in issues

### ISSUE THREAD

**Issue by aleksandra-mazurek** [spicecrm/spicecrm_fe_release_core#3]
On our environment (Ubuntu) log in does not work. You can only do that if you first log in to backand, then if you go to frontend and put random letters into login and password fields you will be logged in as user you just logged in as to backend.

I understand that it may be an infrastructure issue so let me know what kind of information should we provide for you to be able to help us. :)

**Comment by christianknoll** [comment]
the login is handled in the backend in KREST/KRESTManager.php in the method authenticate (line 72). There is several forms of authentication checked. One of the last ones (for backward compatibility with the old UI) is the check for the coockies. As it seems the second login stores the cooockie and you are authenticated by the coockie in the browser rathen then by the basic Auth Header with the request. 

In the first steps the REST Interface checks for $_SERVER Variables ... PHP_AUTH_USER and PHP_AUTH_PW .. then PHP_AUTH_DIGEST_RAW .. it seems this is not sent properly (can vary depending on the config on the Operating System, apache, PHP.

Try to log the SERVER Variables there and let's check if they are sent in other variables. We have seen this before where this e.g. was in different capitalization etc.

**Comment by Simonell** [comment]
Problem was $_SERVER['HTTP_AUTHORIZATION'] variable which doesn't exist. I added specific line to apache2:
`<IfModule setenvif_module>
    SetEnvIfNoCase ^Authorization$ "(.+)" HTTP_AUTHORIZATION=$1
</IfModule>
`
Now it works well. Thanks!

**Comment by christianknoll** [comment]
great
