### ISSUE TITLE
User editview label issues and email field editing

### ISSUE THREAD

**Issue by aleksandra-mazurek** [spicecrm/spicecrm_fe_release_core#4]
In todays development user edit view does not show labels for fields and presents  them as system field names, do not allows for email edit, and userquotas is a text fields instead of checkbox.
![image](https://user-images.githubusercontent.com/18551557/59642725-84126300-9166-11e9-89b2-dec6bc603fe2.png)

**Comment by christianknoll** [comment]
we did see this before (some time ago) when the UI suddenyl looses the module definition ... the problem is that we need a case and way to reproduce this ..

**Comment by aleksandra-mazurek** [comment]
think we can close it. It behaves this way if after installing the instance you download ui config in backend and don't reloade the core configuration later in front end...
