### ISSUE TITLE
Notes in Products

### ISSUE THREAD

**Issue by aleksandra-mazurek** [spicecrm/spicecrm_fe_release_core#6]
Notes in Product shows HTML <br/> when Enter was used
![image](https://user-images.githubusercontent.com/18551557/59643288-60501c80-9168-11e9-9416-197d8b54617e.png)

**Comment by christianknoll** [comment]
pushed a fix for that to the development core branch .. will be here with the next release

**Comment by christianknoll** [comment]
retested and worked
