### ISSUE TITLE
Calendar polish translation 

### ISSUE THREAD

**Issue by aleksandra-mazurek** [spicecrm/spicecrm_fe_release_core#7]
Does calendar widget uses its own translation ? When switched to polish language we get this "czerwca|czerwiec " label but nowhere in our translation we entered labels such as this.

![image](https://user-images.githubusercontent.com/18551557/59643544-609ce780-9169-11e9-917c-206d493106ff.png)

**Comment by christianknoll** [comment]
this comes formt he language setting in moment.js I believe.

**Comment by christianknoll** [comment]
this is actually loaded from moment.js .. in component src/systemcomponents/components/systeminputdatepicker.ts on line 73 ..

**Comment by aleksandra-mazurek** [comment]
seems that if we could change that line to: 
`return moment.localeData().months()[this.curDate.month()];`
it works ok for polish and seems to work ok for other languages as well

**Comment by christianknoll** [comment]
great .. can you change it and commit it to the factory dev branch?

**Comment by christianknoll** [comment]
the next release will it make available here than as well

**Comment by christianknoll** [comment]
change pushed to dev master
